package com.espsa.mobilepos.app.sync;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import com.espsa.mobilepos.core.model.V2Contract;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/** Revalidates a persisted v2 pair without ever opening the snapshot writable. */
public final class V2SnapshotValidator {
    private static final Set<String> TABLES=set("sync_metadata","products","categories","units","promotion_candidates","promotion_candidate_products","promotion_raw_rows","promotion_rules","promotion_rule_tiers","promotion_rule_schedules","promotion_rule_groups","validation_issues");
    private static final Map<String,String[]> COLUMN_SPEC=columnSpec();
    private static final Map<String,Set<String>> COLUMNS=requiredColumns();
    private static SchemaFacts expected(){return ExpectedHolder.VALUE;}
    private static final class ExpectedHolder { static final SchemaFacts VALUE=expectedSchemaFacts(); }
    private final ReadOnlyDatabaseInspector inspector;
    interface ReadOnlyDatabaseInspector { DatabaseFacts inspect(File database) throws Exception; }
    public V2SnapshotValidator(){this(new AndroidReadOnlyDatabaseInspector());}
    V2SnapshotValidator(ReadOnlyDatabaseInspector inspector){if(inspector==null)throw new IllegalArgumentException("Missing database inspector");this.inspector=inspector;}

    V2SnapshotStateStore.SnapshotSummary validate(File database,ComputerSyncManifestV2 manifest,V2SnapshotStateStore.SnapshotSummary expected)throws Exception{
        if(!V2SnapshotStateStore.isRegularFile(database)||manifest==null)throw new IllegalArgumentException("Snapshot object missing or unsafe");
        V2SnapshotStateStore.SnapshotSummary actual=summary(manifest);
        if(expected!=null&&!actual.matches(expected))throw new IllegalArgumentException("State and manifest differ");
        if(database.length()!=actual.sizeBytes||!sha256(database).equals(actual.sha256))throw new IllegalArgumentException("Snapshot object hash or size mismatch");
        DatabaseFacts facts=inspector.inspect(database);
        if(facts==null||facts.userVersion!=V2Contract.SCHEMA_VERSION||!facts.integrityOk||!facts.foreignKeysOk||!TABLES.equals(facts.tables)||!expected().matches(facts.schema))throw new IllegalArgumentException("SQLite structural validation failed");
        if(!facts.columns.keySet().equals(COLUMNS.keySet())||!hasRequiredColumns(facts.columns)||!"2".equals(facts.metadata.get("schemaVersion"))||!manifest.snapshotId().equals(facts.metadata.get("snapshotId"))||!isSourceHash(facts.metadata.get("sourceHash")))throw new IllegalArgumentException("SQLite contract mismatch");
        if(!expectedCounts(manifest.productCount(),manifest.categoryCount(),manifest.unitCount(),manifest.promotionCandidateCount(),manifest.verifiedPromotionCount(),manifest.validationIssueCount()).equals(facts.counts))throw new IllegalArgumentException("SQLite manifest counts mismatch");
        return actual;
    }
    static V2SnapshotStateStore.SnapshotSummary summary(ComputerSyncManifestV2 m){return new V2SnapshotStateStore.SnapshotSummary(m.snapshotId(),m.sha256(),m.sizeBytes(),V2Contract.SCHEMA_VERSION,m.minimumAppVersion(),m.productCount(),m.categoryCount(),m.unitCount(),m.promotionCandidateCount(),m.verifiedPromotionCount(),m.validationIssueCount());}
    static Map<String,Long> expectedCounts(long products,long categories,long units,long candidates,long verified,long issues){Map<String,Long>r=new LinkedHashMap<String,Long>();r.put("products",products);r.put("categories",categories);r.put("units",units);r.put("promotion_candidates",candidates);r.put("promotion_rules",verified);r.put("validation_issues",issues);return Collections.unmodifiableMap(r);}

    static final class DatabaseFacts{
        final int userVersion;final boolean integrityOk,foreignKeysOk;final Set<String>tables;final Map<String,Set<String>>columns;final SchemaFacts schema;final Map<String,String>metadata;final Map<String,Long>counts;
        DatabaseFacts(int v,boolean i,boolean f,Set<String>t,Map<String,Set<String>>c,Map<String,String>m,Map<String,Long>n){this(v,i,f,expected(),t,c,m,n);}
        DatabaseFacts(int v,boolean i,boolean f,SchemaFacts s,Set<String>t,Map<String,Set<String>>c,Map<String,String>m,Map<String,Long>n){userVersion=v;integrityOk=i;foreignKeysOk=f;schema=s;tables=immutableSet(t);columns=immutableColumns(c);metadata=Collections.unmodifiableMap(new LinkedHashMap<String,String>(m));counts=Collections.unmodifiableMap(new LinkedHashMap<String,Long>(n));}
        static DatabaseFacts valid(Map<String,String>m,Map<String,Long>n){return new DatabaseFacts(2,true,true,expected(),TABLES,COLUMNS,m,n);}
    }
    /** Exact, injectable metadata facts.  There is no boolean schema shortcut. */
    static final class SchemaFacts{
        final Map<String,List<ColumnFact>>columns;final List<ForeignKeyFact>foreignKeys;final Map<String,IndexFact>indexes;final boolean candidatesCheck,rulesCandidateUnique;
        SchemaFacts(Map<String,List<ColumnFact>>c,List<ForeignKeyFact>f,Map<String,IndexFact>i,boolean check,boolean unique){columns=immutableFacts(c);foreignKeys=Collections.unmodifiableList(new ArrayList<ForeignKeyFact>(f));indexes=Collections.unmodifiableMap(new LinkedHashMap<String,IndexFact>(i));candidatesCheck=check;rulesCandidateUnique=unique;}
        boolean matches(SchemaFacts a){return a!=null&&columns.equals(a.columns)&&noDuplicates(foreignKeys)&&noDuplicates(a.foreignKeys)&&new HashSet<ForeignKeyFact>(foreignKeys).equals(new HashSet<ForeignKeyFact>(a.foreignKeys))&&indexes.equals(a.indexes)&&candidatesCheck==a.candidatesCheck&&rulesCandidateUnique==a.rulesCandidateUnique;}
    }
    static final class ColumnFact{final int cid,notNull,pk;final String name,type,defaultValue;ColumnFact(int c,String n,String t,int nn,String d,int p){cid=c;name=n;type=t;notNull=nn;defaultValue=d;pk=p;}@Override public boolean equals(Object o){if(!(o instanceof ColumnFact))return false;ColumnFact x=(ColumnFact)o;return cid==x.cid&&notNull==x.notNull&&pk==x.pk&&same(name,x.name)&&same(type,x.type)&&same(defaultValue,x.defaultValue);}@Override public int hashCode(){return hash(cid,name,type,notNull,defaultValue,pk);}}
    static final class ForeignKeyFact{final String table,from,referenceTable,to,onUpdate,onDelete,match;ForeignKeyFact(String a,String b,String c,String d,String e,String f,String g){table=a;from=b;referenceTable=c;to=d;onUpdate=e;onDelete=f;match=g;}@Override public boolean equals(Object o){if(!(o instanceof ForeignKeyFact))return false;ForeignKeyFact x=(ForeignKeyFact)o;return same(table,x.table)&&same(from,x.from)&&same(referenceTable,x.referenceTable)&&same(to,x.to)&&same(onUpdate,x.onUpdate)&&same(onDelete,x.onDelete)&&same(match,x.match);}@Override public int hashCode(){return hash(table,from,referenceTable,to,onUpdate,onDelete,match);}}
    static final class IndexFact{final String table,name;final boolean unique;final List<String>columns;IndexFact(String t,String n,boolean u,List<String>c){table=t;name=n;unique=u;columns=Collections.unmodifiableList(new ArrayList<String>(c));}@Override public boolean equals(Object o){if(!(o instanceof IndexFact))return false;IndexFact x=(IndexFact)o;return unique==x.unique&&same(table,x.table)&&same(name,x.name)&&columns.equals(x.columns);}@Override public int hashCode(){return hash(table,name,Boolean.valueOf(unique),columns);}}

    private static final class AndroidReadOnlyDatabaseInspector implements ReadOnlyDatabaseInspector{
        @Override public DatabaseFacts inspect(File file){SQLiteDatabase db=SQLiteDatabase.openDatabase(file.getAbsolutePath(),null,SQLiteDatabase.OPEN_READONLY);try{Set<String>tables=strings(db,"SELECT name FROM sqlite_master WHERE type='table'");Map<String,Set<String>>columns=new LinkedHashMap<String,Set<String>>();for(String t:TABLES)columns.put(t,columnNames(db,t));Map<String,Long>counts=new LinkedHashMap<String,Long>();for(String t:expectedCounts(0,0,0,0,0,0).keySet())counts.put(t,Long.valueOf(scalarLong(db,"SELECT COUNT(*) FROM ["+t+"]")));return new DatabaseFacts(scalarInt(db,"PRAGMA user_version"),"ok".equals(scalarString(db,"PRAGMA integrity_check")),empty(db,"PRAGMA foreign_key_check"),collectSchema(db),tables,columns,metadata(db),counts);}finally{db.close();}}
        private static SchemaFacts collectSchema(SQLiteDatabase db){Map<String,List<ColumnFact>>columns=new LinkedHashMap<String,List<ColumnFact>>();List<ForeignKeyFact>keys=new ArrayList<ForeignKeyFact>();Map<String,IndexFact>indexes=new LinkedHashMap<String,IndexFact>();for(String t:TABLES){columns.put(t,columnFacts(db,t));keys.addAll(foreignKeys(db,t));indexes.putAll(explicitIndexes(db,t));}String candidates=scalarString(db,"SELECT sql FROM sqlite_master WHERE type='table' AND name='promotion_candidates'");String rules=scalarString(db,"SELECT sql FROM sqlite_master WHERE type='table' AND name='promotion_rules'");return new SchemaFacts(columns,keys,indexes,candidates!=null&&compact(candidates).contains("CHECK(verification_statusIN('VERIFIED','UNVERIFIED','INVALID','UNKNOWN_TYPE','INACTIVE'))"),rules!=null&&compact(rules).contains("CANDIDATE_IDTEXTNOTNULLUNIQUE"));}
        private static List<ColumnFact>columnFacts(SQLiteDatabase db,String table){Cursor c=db.rawQuery("PRAGMA table_info(["+table+"])",null);try{List<ColumnFact>r=new ArrayList<ColumnFact>();while(c.moveToNext())r.add(new ColumnFact(c.getInt(0),c.getString(1),c.getString(2),c.getInt(3),c.isNull(4)?null:c.getString(4),c.getInt(5)));return r;}finally{c.close();}}
        private static List<ForeignKeyFact>foreignKeys(SQLiteDatabase db,String table){Cursor c=db.rawQuery("PRAGMA foreign_key_list(["+table+"])",null);try{List<ForeignKeyFact>r=new ArrayList<ForeignKeyFact>();while(c.moveToNext())r.add(new ForeignKeyFact(table,c.getString(3),c.getString(2),c.getString(4),c.getString(5),c.getString(6),c.getString(7)));return r;}finally{c.close();}}
        private static Map<String,IndexFact>explicitIndexes(SQLiteDatabase db,String table){Cursor c=db.rawQuery("PRAGMA index_list(["+table+"])",null);try{Map<String,IndexFact>r=new LinkedHashMap<String,IndexFact>();while(c.moveToNext()){String name=c.getString(1);if("c".equals(c.getString(3)))r.put(name,new IndexFact(table,name,c.getInt(2)!=0,indexColumns(db,table,name)));}return r;}finally{c.close();}}
        /* Only a frozen expected index name is interpolated into PRAGMA. */
        private static List<String>indexColumns(SQLiteDatabase db,String table,String name){IndexFact e=expected().indexes.get(name);if(e==null||!table.equals(e.table))return Collections.emptyList();Cursor c=db.rawQuery("PRAGMA index_info(["+name+"])",null);try{List<String>r=new ArrayList<String>();while(c.moveToNext())r.add(c.getString(2));return r;}finally{c.close();}}
        private static Set<String>columnNames(SQLiteDatabase db,String t){Set<String>r=new HashSet<String>();for(ColumnFact f:columnFacts(db,t))r.add(f.name);return r;}private static Map<String,String>metadata(SQLiteDatabase db){Cursor c=db.rawQuery("SELECT key,value FROM sync_metadata",null);try{Map<String,String>r=new LinkedHashMap<String,String>();while(c.moveToNext())r.put(c.getString(0),c.getString(1));return r;}finally{c.close();}}private static boolean empty(SQLiteDatabase d,String q){Cursor c=d.rawQuery(q,null);try{return !c.moveToFirst();}finally{c.close();}}private static String scalarString(SQLiteDatabase d,String q){Cursor c=d.rawQuery(q,null);try{return c.moveToFirst()?c.getString(0):null;}finally{c.close();}}private static long scalarLong(SQLiteDatabase d,String q){Cursor c=d.rawQuery(q,null);try{return c.moveToFirst()?c.getLong(0):-1L;}finally{c.close();}}private static int scalarInt(SQLiteDatabase d,String q){Cursor c=d.rawQuery(q,null);try{return c.moveToFirst()?c.getInt(0):-1;}finally{c.close();}}private static Set<String>strings(SQLiteDatabase d,String q){Cursor c=d.rawQuery(q,null);try{Set<String>r=new HashSet<String>();while(c.moveToNext())r.add(c.getString(0));return r;}finally{c.close();}}private static String compact(String s){return s.replaceAll("\\s+","").toUpperCase(java.util.Locale.ROOT);}
    }
    static SchemaFacts expectedSchemaFacts(){Map<String,List<ColumnFact>>c=new LinkedHashMap<String,List<ColumnFact>>();for(Map.Entry<String,String[]>e:COLUMN_SPEC.entrySet()){List<ColumnFact>l=new ArrayList<ColumnFact>();int cid=0;for(String v:e.getValue()){String[]p=v.split("\\|",-1);l.add(new ColumnFact(cid++,p[0],p[1],Integer.parseInt(p[2]),null,Integer.parseInt(p[3])));}c.put(e.getKey(),l);}List<ForeignKeyFact>f=new ArrayList<ForeignKeyFact>();for(String v:FKS){String[]p=v.split("\\|",-1);f.add(new ForeignKeyFact(p[0],p[1],p[2],p[3],p[4],p[5],p[6]));}Map<String,IndexFact>i=new LinkedHashMap<String,IndexFact>();for(String v:INDEXES){String[]p=v.split("\\|",-1);i.put(p[1],new IndexFact(p[0],p[1],Boolean.parseBoolean(p[2]),Arrays.asList(p[3].split(",",-1))));}return new SchemaFacts(c,f,i,true,true);}
    private static String sha256(File f)throws Exception{MessageDigest d=MessageDigest.getInstance("SHA-256");try(BufferedInputStream in=new BufferedInputStream(new FileInputStream(f))){byte[]b=new byte[8192];int n;while((n=in.read(b))!=-1)d.update(b,0,n);}StringBuilder r=new StringBuilder(64);for(byte x:d.digest())r.append(String.format("%02x",x&255));return r.toString();}
    private static boolean hasRequiredColumns(Map<String,Set<String>>a){for(Map.Entry<String,Set<String>>e:COLUMNS.entrySet()){Set<String>v=a.get(e.getKey());if(v==null||!v.containsAll(e.getValue()))return false;}return true;}private static boolean isSourceHash(String v){return v!=null&&v.matches("^[0-9a-f]{64}$");}
    private static final String[]FKS={"products|category_code|categories|category_code|NO ACTION|RESTRICT|NONE","products|unit_code|units|unit_code|NO ACTION|RESTRICT|NONE","promotion_candidate_products|candidate_id|promotion_candidates|candidate_id|NO ACTION|CASCADE|NONE","promotion_candidate_products|source_product_key|products|source_product_key|NO ACTION|RESTRICT|NONE","promotion_raw_rows|candidate_id|promotion_candidates|candidate_id|NO ACTION|CASCADE|NONE","promotion_rules|candidate_id|promotion_candidates|candidate_id|NO ACTION|CASCADE|NONE","promotion_rule_tiers|rule_id|promotion_rules|rule_id|NO ACTION|CASCADE|NONE","promotion_rule_schedules|rule_id|promotion_rules|rule_id|NO ACTION|CASCADE|NONE","promotion_rule_groups|rule_id|promotion_rules|rule_id|NO ACTION|CASCADE|NONE","validation_issues|candidate_id|promotion_candidates|candidate_id|NO ACTION|SET NULL|NONE","validation_issues|source_product_key|products|source_product_key|NO ACTION|SET NULL|NONE"};
    private static final String[]INDEXES={"products|idx_products_barcode|false|barcode","promotion_candidate_products|idx_candidate_products_candidate|false|candidate_id,mapping_order","promotion_raw_rows|idx_raw_rows_candidate|false|candidate_id,source_order","promotion_rule_tiers|idx_tiers_rule|false|rule_id,tier_order","promotion_rule_schedules|idx_schedules_rule|false|rule_id,schedule_order","promotion_rule_groups|idx_groups_rule|false|rule_id,group_order","validation_issues|idx_issues_candidate|false|candidate_id"};
    private static Map<String,String[]>columnSpec(){Map<String,String[]>m=new LinkedHashMap<String,String[]>();m.put("sync_metadata",cols("key|TEXT|0|1","value|TEXT|1|0"));m.put("categories",cols("category_code|TEXT|0|1","category_name|TEXT|1|0","source_order|INTEGER|1|0"));m.put("units",cols("unit_code|TEXT|0|1","unit_name|TEXT|1|0","source_order|INTEGER|1|0"));m.put("products",cols("source_product_key|TEXT|0|1","gid|TEXT|1|0","barcode|TEXT|1|0","secondary_barcode|TEXT|0|0","name|TEXT|1|0","category_code|TEXT|0|0","unit_code|TEXT|0|0","sale_price_raw|TEXT|1|0","sale_price_decimal|TEXT|1|0","simple_price_raw|TEXT|0|0","simple_price_decimal|TEXT|0|0","simple_threshold_raw|TEXT|0|0","simple_threshold_decimal|TEXT|0|0","stop_flag|INTEGER|1|0","source_update_time_local|TEXT|0|0"));m.put("promotion_candidates",cols("candidate_id|TEXT|0|1","source_type|TEXT|1|0","source_key|TEXT|1|0","verification_status|TEXT|1|0","begin_local|TEXT|0|0","end_local|TEXT|0|0","normalized_rule_version|TEXT|0|0","evidence_hash|TEXT|0|0"));m.put("promotion_candidate_products",cols("mapping_id|TEXT|0|1","candidate_id|TEXT|1|0","source_product_key|TEXT|0|0","source_barcode|TEXT|0|0","group_code|TEXT|0|0","mapping_order|INTEGER|0|0"));m.put("promotion_raw_rows",cols("raw_row_id|TEXT|0|1","candidate_id|TEXT|0|0","source_table|TEXT|1|0","source_key|TEXT|1|0","source_order|INTEGER|1|0","original_json|TEXT|1|0","canonical_json|TEXT|1|0"));m.put("promotion_rules",cols("rule_id|TEXT|0|1","candidate_id|TEXT|1|0","rule_type|TEXT|1|0","rule_version|TEXT|1|0","evidence_hash|TEXT|1|0","parameters_json|TEXT|1|0","priority_order|INTEGER|0|0","stack_mode|TEXT|1|0"));m.put("promotion_rule_tiers",cols("tier_id|TEXT|0|1","rule_id|TEXT|1|0","threshold_decimal|TEXT|1|0","value_kind|TEXT|1|0","value_decimal|TEXT|1|0","tier_order|INTEGER|1|0"));m.put("promotion_rule_schedules",cols("schedule_id|TEXT|0|1","rule_id|TEXT|1|0","begin_date_local|TEXT|0|0","end_date_local|TEXT|0|0","weekday|INTEGER|0|0","begin_time_local|TEXT|0|0","end_time_local|TEXT|0|0","schedule_order|INTEGER|1|0"));m.put("promotion_rule_groups",cols("group_id|TEXT|0|1","rule_id|TEXT|1|0","group_code|TEXT|1|0","required_count_decimal|TEXT|1|0","group_order|INTEGER|1|0"));m.put("validation_issues",cols("issue_id|TEXT|0|1","severity|TEXT|1|0","issue_code|TEXT|1|0","candidate_id|TEXT|0|0","source_product_key|TEXT|0|0","message_code|TEXT|1|0","diagnostic_json|TEXT|1|0"));return Collections.unmodifiableMap(m);}private static String[]cols(String...v){return v;}
    private static Set<String>set(String...v){HashSet<String>r=new HashSet<String>();Collections.addAll(r,v);return Collections.unmodifiableSet(r);}private static Set<String>immutableSet(Set<String>v){return Collections.unmodifiableSet(new HashSet<String>(v));}private static Map<String,Set<String>>immutableColumns(Map<String,Set<String>>v){Map<String,Set<String>>r=new LinkedHashMap<String,Set<String>>();for(Map.Entry<String,Set<String>>e:v.entrySet())r.put(e.getKey(),immutableSet(e.getValue()));return Collections.unmodifiableMap(r);}private static Map<String,List<ColumnFact>>immutableFacts(Map<String,List<ColumnFact>>v){Map<String,List<ColumnFact>>r=new LinkedHashMap<String,List<ColumnFact>>();for(Map.Entry<String,List<ColumnFact>>e:v.entrySet())r.put(e.getKey(),Collections.unmodifiableList(new ArrayList<ColumnFact>(e.getValue())));return Collections.unmodifiableMap(r);}private static boolean noDuplicates(List<?>v){return v.size()==new HashSet<Object>(v).size();}private static boolean same(Object a,Object b){return a==null?b==null:a.equals(b);}private static int hash(Object...v){return Arrays.hashCode(v);}private static Map<String,Set<String>>requiredColumns(){Map<String,Set<String>>r=new LinkedHashMap<String,Set<String>>();for(Map.Entry<String,String[]>e:COLUMN_SPEC.entrySet()){Set<String>s=new LinkedHashSet<String>();for(String v:e.getValue())s.add(v.substring(0,v.indexOf('|')));r.put(e.getKey(),Collections.unmodifiableSet(s));}return Collections.unmodifiableMap(r);}
}
